"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
[](bold fg:color_dir_bg bg:color_git_bg)\
$git_branch\
$git_status\
[](bold fg:color_git_bg bg:color_term_bg) """

palette = 'tokyonight'

[palettes.tokyonight]
color_term_bg = '#222436'
color_status_bg = '#3B4261'
color_os_bg = '#C1E68C'
color_os_fg = '#222436'
color_host_bg = '#82AAFF'
color_host_fg = '#3B4261'
color_git_bg = '#C1E68C'
color_git_fg = '#3B4261'
color_dir_bg = '#3B4261'
color_dir_fg = '#C6D1F3'
color_lang_bg = '#82AAFF'
color_lang_fg = '#3B4261'
color_time_bg = '#82AAFF'
color_time_fg = '#3B4261'

[palettes.nord]
color_blue = '#819FC1'
color_green = '#A4BE8F'
color_white = '#E5E9F0'
color_red = '#BF616A'
color_dark_grey = '#585858'
color_light_grey = '#BCBCBC'
color_dark_blue = '#819FC1'
color_black = '#2E3440'

[os]
disabled = false
style = "bg:color_os_bg fg:color_os_fg"

[os.symbols]
Windows = "󰍲 "
Ubuntu = "󰕈 "
Mint = "󰣭 "
Macos = "󰀵 "
Linux = "󰌽 "
Debian = "󰣚 "
FreeBSD = " "
NetBSD = "󰈿 "

[username]
show_always = true
style_user = "bold bg:color_host_bg fg:color_host_fg"
style_root = "bold bg:color_host_bg fg:color_host_fg"
format = '[ $user]($style)'

[hostname]
ssh_only = false
style = "bold bg:color_host_bg fg:color_host_fg"
format = '[@]($style)[$hostname ]($style)'
disabled = false

[directory]
style = "fg:color_dir_fg bg:color_dir_bg"
read_only_style = "bg:color_dir_bg"
#format = "[ $read_only]($read_only_style)[$path ]($style)"
format = "[ $path ]($style)"
truncation_length = 1
truncation_symbol = "  …/"
fish_style_pwd_dir_length = 1
home_symbol = " "

[git_branch]
symbol = ""
style = "bold bg:color_git_bg"
format = '[[ $symbol $branch ](bold fg:color_git_fg bg:color_git_bg)]($style)'

[git_status]
style = "bg:color_git_bg"
format = '[[($all_status$ahead_behind )](bold fg:color_git_fg bg:color_git_bg)]($style)'

[perl]
symbol = " "
style = "bold fg:color_lang_fg bg:color_lang_bg"
format = '([ $symbol ($version )]($style))'
