swipe:
  3:
    left:
      command: "xdotool key alt+Left" # History forward
    right:
      command: "xdotool key alt+Right" # History back
  4:
    left:
      command: "xdotool key ctrl+Left" # Switch to next workspace
    right:
      command: "xdotool key ctrl+Right" # Switch to previous workspace
